-- Categories
-- 1 -> Electronics
-- 2 -> Fashion
-- 3 -> Car & Moto
-- 4 -> Home

INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Iphone 13 Mini', 'Η Apple παρουσιάζει τα iPhone 13 προσφέροντας πρωτοποριακές καινοτομίες σε κάμερα και τσιπ με μεγάλη διάρκεια ζωής της μπαταρίας. Διαθέτει κομψή και ανθεκτική σχεδίαση, προηγμένο νέο σύστημα διπλής κάμερας για κρυστάλλινες φωτογραφίες και βίντεο με ποικιλία φίλτρων για να διαλέξεις αυτό που σου ταιριάζει.', 1, 'Apple', 2021, 'https://i0.wp.com/www.hotspotmob.gr/wp-content/uploads/2022/04/%CE%B5%CE%BA%CE%B8%CE%B5%CF%83%CE%B9%CE%B1%CE%BA%CF%8C-iPhone-13-%CE%BC%CE%B1%CF%8D%CF%81%CE%BF.png?fit=1080%2C1080&ssl=1');
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('S24 Ultra', 'Samsung''s phone', 1, 'Samsung', 2024, 'https://static.vecteezy.com/system/resources/previews/041/329/788/non_2x/samsung-galaxy-s24-ultra-titanium-blue-back-view-free-png.png');
--1452, 
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('AirPods Pro Gen2', 'Apple''s new earphones', 1, 'Apple', 2024, 'https://png.pngtree.com/png-vector/20231104/ourmid/pngtree-apple-airpods-pro-png-image_10477533.png');
--250, 
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Switch OLED (White)', 
'Το Nintendo Switch μπορεί να προσαρμοστεί στις ανάγκες σας, καθώς συνδυάζει την υπολογιστική δύναμη μιας σταθερής κονσόλας με την ευκολία μιας φορητής. Μπορείτε να παίξετε τα παιχνίδια που θέλετε, όσο γεμάτη και να είναι η μέρα σας. H κονσόλα προσαρμόζεται για την κατάσταση που την χρειάζεστε. Απολαύστε τα παιχνίδια όποτε θέλετε, όπου θέλετε, παρέα με όποιον θέλετε με τις ευέλικτες καταστάσεις παιχνιδιού.',
 1, 'Nintendo', 2023, 'https://www.nintendo.com/ph/hardware/switch/regions/img/hardSwitch-nav-OpenMenu-pic03.png');
--325,
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Playstation 5', '', 1, 'Sony', 2023, 'https://www.xgame-stores.com/image/cache/catalog/2021/PS5%20slim%20disk%20edition%20pn2-550x550h.png');


INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Wash & Wax', 'Καθάρισμα σε βάθος και χωρίς κόπο', 3, 'Meguiar''s', 2022, 'https://cdn.shopify.com/s/files/1/0798/2845/1665/files/G17748.png?v=1718128165');
--15.9,
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Rubber Boot Mat for Scirocoo', 'Πατάκι κομμένο ακριβώς στις διαστάσεις του αυτκινήτου', 3, 'Vortex', 2011, 'https://www.roofbox.co.uk/car-boot-liners-mats/images/low-sided-boot-liner.png');
--34.85,

INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Black T-shirt', 'Μαύρο αντρικό μπλουζάκι', 2, 'North Face', 2024, 'https://i.pinimg.com/originals/62/98/b0/6298b026a65cf80bcf9dce061e9b79c9.png');
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('17-cn2002nv 17.3" IPS', 'Το HP 17-cn2002nv είναι ένα notebook με οθόνη 17.3" που απευθύνεται κυρίως σε χρήστες που αναζητούν έναν ισχυρό υπολογιστή για καθημερινή χρήση. Είναι εξοπλισμένο με τον επεξεργαστή Intel Core i5 1235U, χρονισμένο στα 3.3GHz της γενιάς Alder Lake (12th Gen) (2021), και μπορεί να υποστηρίξει πολλές εφαρμογές και παράθυρα πλοήγησης ανοιχτά ταυτόχρονα. Επίσης, διαθέτει ενσωματωμένο κύκλωμα γραφικών που μπορεί να χρησιμοποιηθεί για ελαφρύ gaming1. Συνολικά, το HP 17-cn2002nv προσφέρει μια ισχυρή λύση για χρήστες που απαιτούν υψηλή απόδοση σε καθημερινή βάση.', 1, 'HP', 2023, 'https://purepng.com/public/uploads/large/purepng.com-laptopelectronicslaptopcomputer-941524676379zuw2c.png');
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Edge Synthetic Motor Oil 5W-30', 'Το Castrol EDGE απελευθερώνει τις επιδόσεις και την απόδοση του κινητήρα σας για την παροχή μεγαλύτερης ισχύος με το ίδιο καύσιμο (*).', 3, 'Castrol', 2021, 'https://www.castrol.com/content/dam/castrol/master-site/en/global-ia/home/images/products/reignite-meksa/our-brands/resized-generic-images/edge-eg-pk-1322x2034.png');
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Pilot Sport 5 225/40 R18 92Y', 'Καλοκαιρινό λάστιχο αυτοκινήτου Pilot Sport 5 της εταιρείας Michelin, κατάλληλο για χρήση σε υψηλές θερμοκρασίες. Το συγκεκριμένο λάστιχο διαθέτει διαστάσεις 225/40R18 και δείκτη φορτίου 92 και δείκτη ταχύτητας Y.', 3, 'Michelin', 2024, 'https://dxm.contentcenter.michelin.com/api/wedia/dam/transform/b98rpyxf61b4xdugq1h3a3861w/thumbnailtiny?t=resize&width=400&height=400');
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Wooden Dining Table', 'Newest dining table released by Woowell enough for the entire family.', 4, 'Woodwell', '2019', 'https://www.pngplay.com/wp-content/uploads/7/Wooden-Dining-Table-PNG-HD-Quality.png');
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Golden Mirror', 'Designed mirror for every place.', 4, 'JYSK', '2009', 'https://www.freeiconspng.com/thumbs/mirror-png/silver-mirror-png-6.png');
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Old Skool', 'Tα Vans Ua Old Skool διαθέτουν εξωτερική λαστιχένια σόλα με μοτίβο waffle καθώς και low cut σχεδιασμό για να ταιριάξει εύκολα με όλα τα κομμάτια της γκαρνταρόμπας σου. Ανανέωσε την συλλογή σου με ένα κλασσικό retro παπούτσι με επιρροές από τον κόσμο του skate και το πρώτο που εμφανίστηκε με διακόσμηση την λωρίδα στο πλάι!', 2, 'Vans', 2009, 'https://pngimg.com/d/vans_PNG13.png');

INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Primacy 5 235/40 R18 91W', 'Αποκτήστε ασφάλεια υψηλού επιπέδου, από το πρώτο μέχρι το τελευταίο χιλιόμετρο(1) με το MICHELIN PRIMACY 4+.Σχεδιασμένο για να προσφέρει ασφάλεια σε εσας και τους συνεπιβάτες σας, σε κάθε σας χιλιόμετρο.', 3, 'Michelin', 2024, 'https://dxm.contentcenter.michelin.com/api/wedia/dam/transform/b98rpyxf61b4x5gnqyc18zt8uw/pim_largepreview?t=resize&width=1000');
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Ultimate Waterless Wash & Wax', 'No need for hose and bucket! The perfect product for urban dwellers. Cleans & shines in less than 15min, without a drop of water!', 3, 'Meguiar''s', 2022, 'https://www.meguiars.gr/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/g/3/g3626eu_wshanywheretrig.png');


INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Apple Watch SE', 'Προηγμένες λειτουργίες που θα σε βοηθήσουν να παραμείνεις συνδεδεμένος, δραστήριος, υγιής και ασφαλής.', 1, 'Apple', 2023, 'https://bsimg.nl/images/apple-watch-se-2023-44mm-zwart-zwarte-siliconenband-m-l-_3.png/6uHWODFLMkUiwwYB5pdRMNFwIuM%3D/fit-in/0x0/filters%3Aupscale%28%29');
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Macbook Pro 14" M4', 'Το MacBook Pro 14 ιντσών με το M4 chip προσφέρει θεαματική απόδοση. Με διάρκεια λειτουργίας της μπαταρίας2 έως 24 ώρες και μια εντυπωσιακή οθόνη Liquid Retina XDR με μέγιστη φωτεινότητα έως και 1600 nits, είναι επαγγελματικό σε κάθε επίπεδο.', 1, 'Apple', 2024, 'https://parspng.com/wp-content/uploads/2023/02/laptoppng.parspng.com-5.png');
INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Apple Pencil USB-C', 'To Apple Pencil (USB-C) είναι τέλειο για να κρατάς σημειώσεις, να σκιτσάρεις, να συμπληρώνεις έγγραφα και άλλα πολλά. Προσφέρει ακρίβεια σε επίπεδο pixel, χαμηλή καθυστέρηση καθώς και tilt sentitivity, που αναγνωρίζει από μια γωνία κρατάτε το Apple Pencil ώστε να αλλάζει ο τρόπος γραφής, σαν να κρατάς ένα πραγματικό μολύβι ή μαρκαδόρο.', 1, 'Apple', 2022, 'https://molla.al/wp-content/uploads/2020/10/pencil-2nd.png');

INSERT INTO Products (Name, Description, CategoryID, Brand, Year, IMAGEURL) VALUES ('Deluxe Pomade 100gr', 'Πομάδα με δυνατό κράτημα και κατάλληλη ποσότητα λάμψης που φεύγει εύκολα με το λούσιμο. Οι χρήστες που το έχουν αγοράσει το ξεχωρίζουν κυρίως γιατί έχει ωραίο άρωμα και έχει εύκολη εφαρμογή.', 2, 'Uppercut', 2015, 'https://privehair.gr/image/cache/catalog/catalog/100/uppercut_pomade_top-500x500-600x315h.png');